### ISSUE TITLE
Passwords on the command line are bad

### ISSUE THREAD

**Issue by viyh** [mayflower/docker-ls#2]
The password should be prompted for upon run, or used from the ~/.docker/config.json file. Passing a password on the command line is very insecure.

**Comment by DirtyHairy** [comment]
Hi @viyh,

thank you for your input!

If you are afraid of sneaky coworkers scraping your passwords from your screen with their prying eyes or gremlins digging through your shell history, you can always use `read -s` to securely read the password into an environment variable, so I do not consider this a serious issue. Nevertheless, prompting for passwords actually _is_ on my list for future improvements, I just cannot honestly tell when I will find time. I'm happy to merge pull requests though :smirk:

As for reading the credentials from `~/.docker/config.json`: I am not fond about reading another programs config, so that's a 'no' there (also, I detest the idea of storing passwords in plaintext).

Cheers
    -Christian

**Comment by jheiss** [comment]
Putting the password into an environment variable and then running `docker-ls --password $pw` still exposes your password to any other user who runs ps.

`docker login` has the same problem unfortunately.

Adding support for reading the password from stdin or from a file would be great.

**Comment by elifarley** [comment]
@viyh If you really want to reuse auth information that the standard Docker executable uses (as I do), consider this Linux shell function (you have to install [jq](http://stedolan.github.io/jq/) first):

``` shell
docker_auth_ls() {
  local cmd="$1"; shift
  local repo="$1"; shift
  local lpw="$(jq -r '.auths["https://index.docker.io/v1/"].auth' ~/.docker/config.json | base64 -d)"
  docker-ls "$cmd" --user "${lpw%:*}" --password "${lpw#*:}" "$repo"
}
```

Usage example:
`docker_auth_ls tags stuff/busybox`

**Comment by DirtyHairy** [comment]
dd1745d01d9996abd2dccfc22e9c16a4a0476806 adds a new option `--interactive-password` for reading the password from an interactive prompt instead of the command line.
