### ISSUE TITLE
docker-ls and registry.gitlab.com

### ISSUE THREAD

**Issue by milkpirate** [mayflower/docker-ls#36]
Hey, as you might know Gitlab.com has a powerful CI and also supplies a private docker registry (per repo). So, pushing images to the registry works like a charm from the CI after a

```bash
$ DOCKER_REGISTRY=registry.gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
$ echo "$REGISTRY_API_TOKEN" | docker login "$CI_REGISTRY" --username "$CI_PROJECT_NAMESPACE" --password-stdin
```

Locally I can even pull my built images after issuing the commands above... but I cant `docker-ls` the tags in the repo... I tried may combination like:

```bash
$ docker-ls tags --registry https://registry.gitlab.com --user <gilab user> --password "$REGISTRY_API_TOKEN"
requesting list . done
authorization rejected by registry
$ docker-ls tags --registry https://<gitlab user>:$REGISTRY_API_TOKEN@registry.gitlab.com/<gitlab user> ${CI_PROJECT_NAME}
requesting list . done
authentication against auth server failed with code 403
$ docker-ls tags --registry https://registry.gitlab.com --user <gilab user> --password $REGISTRY_API_TOKEN <gilab user>/${CI_PROJECT_NAME}
requesting list . done
<gilab user>/${CI_PROJECT_NAME}: no such repository
```

Could you help me out?

**Comment by stesie** [comment]
I wonder if this is just an issue w/ Gitlab's token issuer, since if I run `docker-ls` like so:

```
docker-ls repositories -r https://registry.gitlab.com -u stesie23 -p "$GITLAB_PASS"
```
... then the preauth call requests `Www-Authenticate:[Bearer realm="https://gitlab.com/jwt/auth",service="container_registry",scope="registry:catalog:*"]`

docker-ls then (correctly) requests a jwt token from `https://gitlab.com/jwt/auth?scope=registry%3Acatalog%3A%2A&service=container_registry` (providing basic auth).

... which issues a token like the following:

```
{
  access: [],
  jti: 'a27d1692-8fed-406d-ade8-7f26ece68599',
  aud: 'container_registry',
  sub: 'stesie23',
  iss: 'omnibus-gitlab-issuer',
  iat: 1607005773,
  nbf: 1607005768,
  exp: 1607006673
}
```

... which includes the service name, yet lacks the required scope (notice that `access` property is empty).

... and as a matter of that the next call fails with `error="insufficient_scope"`

**Comment by stesie** [comment]
According to https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/14751

> Since disclosing all repositories in the registry could be considered a security leak, this scope can be issued only to GitLab admins.

**Comment by milkpirate** [comment]
Ahh too bad. Ok, still thank you!

**Comment by stesie** [comment]
yet listing the tags of a single repository should/does work (i.e. call three from above):

```
$ docker-ls tags stesie23/test -r https://registry.gitlab.com -u stesie23 -p "$GITLAB_PASS"
requesting list . done
repository: stesie23/test
tags:
- blub
```
